name: Node.js CI with PostgreSQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.5
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: defaultdb
        ports:
          - 5434:5432
        # Set health check options
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm ci

      - name: Setup Environment Variables
        run: |
          echo "DATABASE_URL=postgresql://user:password@localhost:5434/defaultdb" >> $GITHUB_ENV

      - name: Run Prisma Migrate
        run: npx prisma migrate deploy

      - name: Seed Database
        run: npx prisma db seed

      - name: Run Tests
        run: npm test
